config/routes.rb
Odot::Application.routes.draw do
  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout

  resources :users
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root 'todo_lists#index'

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Thanks for logging in!"
      redirect_to todo_lists_path
    else
      flash[:error] = "There was a problem logging in. Please check your email and password."
      render action: 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    reset_session
    redirect_to root_path, notice: "You have been logged out."
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<h1>Log In</h1>
<%= form_tag user_sessions_path do %>
  <%= label_tag :email, "Email Address" %>
  <%= text_field_tag :email, params[:email] %>
  <br />

  <%= label_tag :password, "Password" %>
  <%= password_field_tag :password %>
  <br />

  <%= submit_tag "Log In" %>
  <%= link_to "Forgot Password", new_password_reset_path %>
<% end %>